Adding scheme to URL to support https in info.json
zimeon/iiif pull request #52
Opened 2021-03-05 23:45 UTC by glenrobson

This was raised in the cookbook meetings and is starting to cause mixed content errors with Mirador. The IIIF reference implementation is hosted over https but the info.json points to http. See the following example:

https://iiif.io/api/image/3.0/example/reference/918ecd18c2592080851777620de9bcb5-gottingen/info.json

This pull requests adds a `scheme` parameter to the config.

2021-03-06 00:18 UTC, glenrobson commented
Fixes: https://github.com/zimeon/iiif/issues/36#issuecomment-553193501

2021-03-08 14:08 UTC, zimeon requested changes

2021-03-08 14:08 UTC, zimeon commented on iiif/flask_utils.py
> +    if port != 80 and port != 443:
I think this this should really be:

```
if not ((port == 80 and scheme == 'http') or (port == 443 and scheme == 'https')):
```

2021-04-25 23:35 UTC, glenrobson commented on iiif/flask_utils.py
> +    if port != 80 and port != 443:
Thanks Simeon, I've made that change.

2021-05-05 13:45 UTC, zimeon approved these changes

2021-05-05 15:11 UTC, merged